Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda/envs/test/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
struct_gb_1.show.all()
------------------

----- stdout -----
Install plotly for visualisation
Install ipyvolume for visualisation
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mUnboundLocalError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m [43mstruct_gb_1[49m[38;5;241;43m.[39;49m[43mshow[49m[38;5;241;43m.[39;49m[43mall[49m[43m([49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyscal3/operations/visualize.py:333[0m, in [0;36mplot_simple[0;34m(sys, colors, radius, opacity)[0m
[1;32m    331[0m box [38;5;241m=[39m sys[38;5;241m.[39mbox[38;5;241m.[39mcopy()
[1;32m    332[0m origin [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;241m0[39m,[38;5;241m0[39m,[38;5;241m0[39m])
[0;32m--> 333[0m traces [38;5;241m=[39m [43mcreate_box_plot[49m[43m([49m[43mbox[49m[43m,[49m[43m [49m[43morigin[49m[43m)[49m
[1;32m    335[0m [38;5;28;01mfor[39;00m key [38;5;129;01min[39;00m comp_ints[38;5;241m.[39mkeys():
[1;32m    336[0m     data[38;5;241m=[39mgo[38;5;241m.[39mScatter3d(
[1;32m    337[0m         x[38;5;241m=[39msys[38;5;241m.[39matoms[38;5;241m.[39mpositions[:,[38;5;241m0[39m][sys[38;5;241m.[39matoms[38;5;241m.[39mtypes [38;5;241m==[39m key],
[1;32m    338[0m         y[38;5;241m=[39msys[38;5;241m.[39matoms[38;5;241m.[39mpositions[:,[38;5;241m1[39m][sys[38;5;241m.[39matoms[38;5;241m.[39mtypes [38;5;241m==[39m key],
[0;32m   (...)[0m
[1;32m    350[0m         )
[1;32m    351[0m     )

File [0;32m/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyscal3/operations/visualize.py:44[0m, in [0;36mcreate_box_plot[0;34m(box, origin)[0m
[1;32m     42[0m traces [38;5;241m=[39m []
[1;32m     43[0m [38;5;28;01mfor[39;00m face [38;5;129;01min[39;00m faces:
[0;32m---> 44[0m     trace [38;5;241m=[39m [43mgo[49m[38;5;241m.[39mScatter3d(
[1;32m     45[0m         x[38;5;241m=[39mface[:,[38;5;241m0[39m],
[1;32m     46[0m         y[38;5;241m=[39mface[:,[38;5;241m1[39m],
[1;32m     47[0m         z[38;5;241m=[39mface[:,[38;5;241m2[39m],
[1;32m     48[0m         mode[38;5;241m=[39m[38;5;124m'[39m[38;5;124mlines[39m[38;5;124m'[39m,
[1;32m     49[0m         name[38;5;241m=[39m[38;5;124m'[39m[38;5;124mlines[39m[38;5;124m'[39m,
[1;32m     50[0m         line[38;5;241m=[39m[38;5;28mdict[39m(width[38;5;241m=[39m[38;5;241m2.0[39m, color[38;5;241m=[39m[38;5;124m'[39m[38;5;124m#263238[39m[38;5;124m'[39m),
[1;32m     51[0m         showlegend[38;5;241m=[39m[38;5;28;01mFalse[39;00m
[1;32m     52[0m     )
[1;32m     53[0m     traces[38;5;241m.[39mappend(trace)
[1;32m     54[0m [38;5;28;01mreturn[39;00m traces

[0;31mUnboundLocalError[0m: local variable 'go' referenced before assignment

